
                        <p><em><small style="font-size:11px!important;">This e-mail was automatically generated by <a style="color:#000; font-size:11px !important;" href="<?=config('site_url')?>" target="_blank"><?=config('name')?></a>. Responding to this e-mail is not possible.</small></em></p>
					</td>
				</tr>
		   </table>
		</td>
	</tr>
</table>

</body>
</html>